### ISSUE TITLE
Support for Chainer 2.0

### ISSUE THREAD

**Issue by harsha-surukam** [aonotas/deep-crf#2]
There are issues running the current build, due to code-breaking changes introduced in Chainer version 2.0.  We should specify the chainer version during the installtion process as 1.24.0 or make changes to the existing code to support v2.

@aonotas, Let me know if you need me to send a pull request.

**Comment by himkt** [comment]
hi @harsha-surukam and @aonotas, I have edited deep-crf for chainer v2 support last week.
so I make the [pull request](https://github.com/aonotas/deep-crf/pull/3).
please tell me if there are something wrong... (I am newbie to chainer.

**Comment by harsha-surukam** [comment]
@himkt I guess, you have commented out the problematic parts. This definitely works, but, the better solution imho would be to upgrade from v1 to v2 according to the [guide].(http://docs.chainer.org/en/stable/upgrade.html).

**Comment by himkt** [comment]
@harsha-surukam thanks for reply 😃 
I understand that it needs to follow the upgrade guide, I close the pull request.

**Comment by aonotas** [comment]
@harsha-surukam Thank you for your comments!
If you have edited v2 support, please send me PR.

**Comment by aonotas** [comment]
I think we need fix deep-crf code following points:
- `train` argument in dropout
- `volatile ` argument in Variable
- `use_cudnn ` argument in L.NStepBiLSTM

Should we switch code according to `chainer.__version__`?

**Comment by harsha-surukam** [comment]
Yes, I think that should help identify the installed version of chainer. But, I'm not sure if it's a good idea to have two branches in the code, based on the version of a library. Is it the best practice? 

Or, should we just enforce people to upgrade chainer? Because, currently the default chainer version installed is 2.0.

**Comment by aonotas** [comment]
I asked Chainer developer just now. 
He told me that we need to branch code based on `chainer.__version__`.

**Comment by harsha-surukam** [comment]
Cool. Let me send you a PR in a bit.

**Comment by aonotas** [comment]
Thank you for your help!!

**Comment by aonotas** [comment]
Hi @harsha-surukam 

Now deep-crf can run on v2.0 and v1.24.0!
