### ISSUE TITLE
Will it support Chainer v3.0.0?

### ISSUE THREAD

**Issue by massongit** [aonotas/deep-crf#39]
I plan to use it for fine-tuning. However, `L.NStepBiLSTM` can be fine-tuning only in __Chainer v 3.0.0 or later__. This is because `__init__` function of neural networks for fine tuning must have two parameters `initialW` and `initial_bias`. So I would like to ask if it supports __Chainer v 3.0.0__.

**Comment by aonotas** [comment]
I'm sorry for the late reply.
>> L.NStepBiLSTM can be fine-tuning only in Chainer v 3.0.0 or later.
I think v 2.00 can also fine-tuning.

```
# load model
serializers.load_hdf5(model_filename, net)

# re-train (fine-tuning)
```

**Comment by massongit** [comment]
Thank you for your reply.
I would like to think about the experimental method based on your advice.
