### ISSUE TITLE
input idx not exposed as a cmd line argument

### ISSUE THREAD

**Issue by harsha-surukam** [aonotas/deep-crf#4]
The example under [Additional Feature Support](https://github.com/aonotas/deep-crf#additional-feature-support) in the readme, mentions arguments −−input idx and −−output idx, that are not handled yet.

This is definitely a great functionality to have, since it would be possible to ignore metadata fields from the raw data files.

**Comment by aonotas** [comment]
OK. I will fix it.

**Comment by aonotas** [comment]
Hi @harsha-surukam @renweibo 

I have done this issues.

First,  please update deep-crf.
```
cd deep-crf
git pull
python setup.py install
```

Second, please following commands:
```
deep-crf train input_file_multi.txt --input_idx 0,1 --output_idx 2 --n_layer 1 --max_iter 30 --optimizer sgd_mom --save_dir save_model_dir --weight_decay 0.05 --delimiter ' ' --gpu 0 --model_name bilstm-cnn-crf --dev_file input_file_multi_dev.txt
```

```
$ cat input_file_multi.txt
Barack  NN B−PERSON 
Hussein NN I−PERSON 
Obama   NN E−PERSON
is      VBZ O 
a       DT  O 
man     NN  O 
.       .   O

Yuji  NN B−PERSON 
Matsumoto NN E−PERSON 
is      VBZ O 
a       DT  O 
man     NN  O 
.       .   O
```
Please see README.md more details!
https://github.com/aonotas/deep-crf/blob/master/README.md
