### ISSUE TITLE
What is the required packages with version ?

### ISSUE THREAD

**Issue by IITtense** [aonotas/deep-crf#56]
I have tried to install it by instructed README file, but I always get error:
In file included from /tmp/easy_install-btbh8apr/h5py-2.7.1/h5py/defs.c:569:0:
/tmp/easy_install-btbh8apr/h5py-2.7.1/h5py/api_compat.h:27:18: fatal error: hdf5.h: No such file or directory
compilation terminated.
error: Setup script exited with error: command 'gcc' failed with exit status 1
Can anybody help me to out from this.

**Comment by massongit** [comment]
@IITtense If you use Ubuntu, you try to run `sudo apt install libhdf5-dev` before installing deep-crf.

**Comment by IITtense** [comment]
Thanks, Its work but when I execute train command then it shows error(I am using Python 2.7 in Ubuntu 64x machine) even my input file(train, dev, test) is copied to the same folder(deep-crf-master).

return callback(*args, **kwargs)
  File "build/bdist.linux-x86_64/egg/deepcrf/__init__.py", line 66, in train
  File "build/bdist.linux-x86_64/egg/deepcrf/main.py", line 102, in run
ValueError: Invalid training sizes: 0 sentences.

**Comment by massongit** [comment]
@IITtense Please tell me about the execution command and the input file.
