### ISSUE TITLE
Will it support Python 3.x?

### ISSUE THREAD

**Issue by massongit** [aonotas/deep-crf#8]
Currently it seems to support only Python 2.x, but will it also support Python 3.x?

**Comment by aonotas** [comment]
I think you can use Python 3.x.
Which code causes problems in v3?

Actually I don't use Python 3.x.
Could you tell me your opinion?

**Comment by tianjianjiang** [comment]
Chainer v2.1.0 source code says it won't work with Python 3.5.0, so I guess the latest working Python 3.x would be 3.4.8.

**Comment by massongit** [comment]
@tianjianjiang  I confirmed that Chainer v.2.1.0 and v1.24.0 source codes say it won't work with Python 3.5.0.
https://github.com/chainer/chainer/blob/7ce9222db1b47e9a48827c3fe432305eef18f6b3/setup.py#L13-L17
https://github.com/chainer/chainer/blob/cfde882b8ceef7c5113a3a3c899922d29aacd631/setup.py#L13-L17

**Comment by tianjianjiang** [comment]
I've tested with `3.5.2` and `3.6.3`, seems working, but with one caveat: for unknown reason (I didn't investigate further), `pip chainer==2.1.0` didn't check the compatible version of `cupy`, which should be `1.0.3`. pip of `3.4.8` and `2.7.12`, however, verified this dependency correctly.
